#if !canImport(ObjectiveC)
import XCTest

extension ChordClusterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChordClusterTests = [
        ("testChordCluster", testChordCluster),
    ]
}

extension ChordClusterViewTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChordClusterViewTests = [
        ("testLayoutMoreComplicated", testLayoutMoreComplicated),
        ("testLayoutMultiNested", testLayoutMultiNested),
        ("testLayoutSingle", testLayoutSingle),
        ("testLayoutThreePairs", testLayoutThreePairs),
        ("testLayoutThreeTrios", testLayoutThreeTrios),
        ("testLayoutTonicDominant", testLayoutTonicDominant),
        ("testLayoutTonicDominantVertical", testLayoutTonicDominantVertical),
        ("testLayoutTonicPredominantDominantVertical", testLayoutTonicPredominantDominantVertical),
        ("testLayoutTonicTwoPredominantDominantVertical", testLayoutTonicTwoPredominantDominantVertical),
        ("testLayoutTwoPairs", testLayoutTwoPairs),
        ("testPointsFromCentroidSinglePoint", testPointsFromCentroidSinglePoint),
        ("testTwoPointsFromCentroidAt90DegreeAngle", testTwoPointsFromCentroidAt90DegreeAngle),
        ("testTwoPointsFromCentroidAtZeroAngle", testTwoPointsFromCentroidAtZeroAngle),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ChordClusterTests.__allTests__ChordClusterTests),
        testCase(ChordClusterViewTests.__allTests__ChordClusterViewTests),
    ]
}
#endif
