#if !canImport(ObjectiveC)
import XCTest

extension HarmonicPathfinderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HarmonicPathfinderTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HarmonicPathfinderTests.__allTests__HarmonicPathfinderTests),
    ]
}
#endif
